name: Daily German Bot

on:
  schedule:
    - cron: "0 7 * * *"  # 독일 아침 8시 (UTC+1 기준 7시)
    - cron: "0 19 * * *"  # 독일 저녁 8시 (UTC+1 기준 19시)
  workflow_dispatch:
  push:
    branches: [main]
  
jobs:
  daily-send:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Install dependencies
        run: go mod tidy

      - name: Run Bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        run: go run main.go

      - name: Commit changes
        run: |
          git config user.name "sinramyeon"
          git config user.email "esistkalt@naver.com"

          git add chat_ids.json
          git add user_progress/

          if ! git diff --cached --quiet; then
            git commit -m "Update chat_ids and user progress [skip ci]"
            git push
          else
            echo "No changes to commit"
          fi